name: Report Issue
description: Report an issue
labels: ["issue"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify and fix the bug

  - type: checkboxes
    attributes:
      label: "Is there an existing issue for this?"
      description: Please search to see if an issue already exists for the bug you encountered
      options:
      - label: I have searched and didn't find similar issue
        required: true

  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: When I click here this happens
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to page X
        2. Click here
        3. Click there
    
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen

  - type: textarea
    id: screenshots
    attributes:
      label: Insert any pictures or video demonstrating the issue. (optional)
  
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.